/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package physics;

public class launchJNI {
  public final static native long new_Launcher(double jarg1, double jarg2, double jarg3);
  public final static native double Launcher_getSpeed(long jarg1, Launcher jarg1_);
  public final static native double Launcher_getGravity(long jarg1, Launcher jarg1_);
  public final static native double Launcher_getVX(long jarg1, Launcher jarg1_);
  public final static native double Launcher_getVY(long jarg1, Launcher jarg1_);
  public final static native double Launcher_getAngle(long jarg1, Launcher jarg1_);
  public final static native void delete_Launcher(long jarg1);
}
