/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package physics;

public class Launcher {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Launcher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Launcher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        launchJNI.delete_Launcher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Launcher(double arg0, double arg1, double arg2) {
    this(launchJNI.new_Launcher(arg0, arg1, arg2), true);
  }

  public double getSpeed() {
    return launchJNI.Launcher_getSpeed(swigCPtr, this);
  }

  public double getGravity() {
    return launchJNI.Launcher_getGravity(swigCPtr, this);
  }

  public double getVX() {
    return launchJNI.Launcher_getVX(swigCPtr, this);
  }

  public double getVY() {
    return launchJNI.Launcher_getVY(swigCPtr, this);
  }

  public double getAngle() {
    return launchJNI.Launcher_getAngle(swigCPtr, this);
  }

}
