/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class physics_Physics */

#ifndef _Included_physics_Physics
#define _Included_physics_Physics
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
