/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class physics_Physics */

#ifndef _Included_physics_Physics
#define _Included_physics_Physics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     physics_Physics
 * Method:    computePeak
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Physics_computePeak
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     physics_Physics
 * Method:    computeTime
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Physics_computeTime
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
