/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class physics_Launcher */

#ifndef _Included_physics_Launcher
#define _Included_physics_Launcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     physics_Launcher
 * Method:    createLaunch
 * Signature: (DDD)J
 */
JNIEXPORT jlong JNICALL Java_physics_Launcher_createLaunch
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     physics_Launcher
 * Method:    destroyLaunch
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_physics_Launcher_destroyLaunch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     physics_Launcher
 * Method:    setSpeedC
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_physics_Launcher_setSpeedC
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     physics_Launcher
 * Method:    getSpeedC
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Launcher_getSpeedC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     physics_Launcher
 * Method:    setAngleC
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_physics_Launcher_setAngleC
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     physics_Launcher
 * Method:    getAngleC
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Launcher_getAngleC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     physics_Launcher
 * Method:    setGravityC
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_physics_Launcher_setGravityC
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     physics_Launcher
 * Method:    getGravityC
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Launcher_getGravityC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     physics_Launcher
 * Method:    getVXC
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Launcher_getVXC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     physics_Launcher
 * Method:    getVYC
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_physics_Launcher_getVYC
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
